language: php

compiler:
  - gcc
  - clang

os:
  - linux

php:
  - 7.0
  - 7.1
  - 7.2

notifications:
  email: dev@service.viest.me

before_script:
  - sudo apt-get install zlib1g-dev -y
  - git clone https://github.com/jmcnamara/libxlsxwriter.git
  - make -C ./libxlsxwriter && sudo make -C ./libxlsxwriter install
  - phpize && ./configure && make clean && make

branches:
  only:
    - master
    - dev
script:
    - ./travis/run-test.sh
